### ISSUE TITLE
Support for solution folders?

### ISSUE THREAD

**Issue by amerkoleci** [Protobuild/Protobuild#154]
Does Protobuild support for solution folders? I want to group projects in given solution folder for better reading in VisualStudio?

**Comment by tomspilman** [comment]
There have been previous failed attempts at it... see https://github.com/hach-que/Protobuild/pull/38.

But I don't believe Protobuild supports it yet.  It would be nice to have in some cases.

**Comment by hach-que** [comment]
Yeah there's no support for solution folders. I've never had enough projects the warrant the investment of implementing the feature, and the last time someone raised the issue was well over a year ago. 

I'm happy to review PRs for it; have a look at what Tom linked as an idea on how it needs to be done.

**Comment by hach-que** [comment]
This is now supported by setting the `IDEFolder` property on the project definition, for example:

```
<Properties>
  <Property Name="IDEFolder" Value="SomeFolder\Blah" />
</Properties>
```
