### ISSUE TITLE
iOS/tvOS Platforms and Configs

### ISSUE THREAD

**Issue by tomspilman** [Protobuild/Protobuild#166]
The current project generation creates the following platforms and configs for iOS/tvOS projects:
 
   - Debug - iPhone
   - Release - iPhone
   - Ad-Hoc - iPhone
   - AppStore - iPhone
   - Debug - iPhoneSimulator
   - Release - iPhoneSimulator

You can see all this here:

https://github.com/Protobuild/Protobuild/blob/master/Protobuild.Internal/BuildResources/GenerateProject.CSharp.xslt#L1185

While these configurations are needed for executable builds...  they don't seem to serve any purpose when building a C# library project.  A simple `Debug - Any CPU` and `Release - Any CPU` is all that is needed for library projects.

It is the application/executable project that is the only one that requires these extra configurations.  These deal with how the AOT process is done and how/if the package is created for deployment.

Would it not be simpler to not generate these configurations on libraries?

**Comment by tomspilman** [comment]
@dellis1972 - Thoughts?

**Comment by hach-que** [comment]
I don't think much of it matters; when you're building an iOS solution the configuration selector will be picking the configuration for all the projects in the solution, not just the libraries.  It would actually be more complex from a Protobuild perspective to generate different configuration mappings between the solution and projects based on their type, as we don't do that anywhere yet.

(also, you'll always end up with those 6 options in the solution level, regardless of whether we make the projects themselves only have two configurations; so you don't really end up simplifying much because the solution needs to be able to handle having application projects in there)

**Comment by tomspilman** [comment]
> generate different configuration mappings

 Yeah...   by default VS will map things correctly just matching `Debug`s ands `Release`s, but if you do that without a mapping you'll have a dirty solution when first opened and would require a save.  That wouldn't be ideal.

> also, you'll always end up with those 6 options in the solution level

Well when the solution is one just for the library... like MonoGame...  it is simpler.  Currently our build scripts build `Release\|iPhoneSimulator` and ship that assembly for iOS just because we have to pick one.

**Comment by hach-que** [comment]
Yeah I pretty much treat `iPhoneSimulator` as `Any CPU` in my stuff as well.  I'm not sure if this it the _correct_ mapping though.

**Comment by tomspilman** [comment]
> I'm not sure if this it the correct mapping though.

I think if we examine the final output assemblies for library projects they are all the same except for some trivial build differences.

**Comment by hach-que** [comment]
I'm going to close this task off.

Implementing this feature would increase complexity (see above) and there doesn't seem to be a real benefit to defining only two configurations for library projects under iOS, because the solution must still contain 6 configurations anyway.

If anyone has any scenarios which are impacted by the additional configurations existing, feel free to open another task.
