### ISSUE TITLE
Import Project for Xamarin.Android

### ISSUE THREAD

**Issue by takeshich** [Protobuild/Protobuild#185]
Hi there,
I'm using Protobuild with Xamarin.Android now for a few weeks and it's really a great tool.

There are two suggestions.

Firstly, in the project file for Xamarin.Android, Import Project is generated as 
`<Import Project="$(MSBuildExtensionsPath)\Novell\Novell.MonoDroid.CSharp.targets" />`
instead of 
`<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />` .

Looking at the file($(MSBuildExtensionsPath)\Novell\Novell.MonoDroid.CSharp.targets),
```XML
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
</Project>
```
it is now an alias of `<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />`, and the file may be deleted in the near future.

One of the members of the Xamarin.Android team said that the `$(MSBuildExtensionsPath)\Novell\Novell.MonoDroid.CSharp.targets` will be deleted in the near future.
https://teratail.com/questions/56804
(Sorry written in Japanese)

I think it would be better to change from `<Import Project="$(MSBuildExtensionsPath)\Novell\Novell.MonoDroid.CSharp.targets" />` to `<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />` .

Secondly, in the project file for Xamarin.android, AndroidSupportedAbis is generated as
`<AndroidSupportedAbis>armeabi,armeabi-v7a,x86</AndroidSupportedAbis>`
 instead of
`<AndroidSupportedAbis>armeabi,armeabi-v7a,arm64-v8a,x86,x86_64</AndroidSupportedAbis>`.

Now,Xamarin.Android supports the following architectures:
* armeabi
* armeabi-v7a
* arm64-v8a
* x86
* x86_64

https://developer.xamarin.com/guides/android/application_fundamentals/cpu_architectures/

I think it would be better to change it ,but I also know that I can customize it by extracting the template and changing it.

Thanks ✋

**Comment by hach-que** [comment]
Thanks for letting me know.  I'll add a "does the new file exist" check so that anyone with new enough versions of Xamarin will get the import to `Xamarin\Android\Xamarin.Android.CSharp.targets` instead (and also include the new supported ABIs based on the same check, unless there's some more reasonable support indicator).

**Comment by hach-que** [comment]
I've sent a PR; if you want to test the built version of `Protobuild.exe` with the change (it would be appreciated if you could), download Protobuild from https://github.com/hach-que/Protobuild/raw/android-targets/Protobuild.exe.  Note that to test it, you should temporarily move your XSLT custom files so that it uses the XSLT in Protobuild itself.

While I've done some basic testing (ran generate, saw it use the new file path, renamed `Xamarin.Android.CSharp.targets` on my computer, ran generate, saw it use the old path), it'd be greatly appreciated if you could test that this works for building Android applications (which I have not done).

**Comment by takeshich** [comment]
I tested in my own environment using the new one.

In my project file for Xamarin.Android, Import Project and AndroidSupportedAbis were generated as 
`<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />`
and
`<AndroidSupportedAbis>armeabi,armeabi-v7a,arm64-v8a,x86,x86_64</AndroidSupportedAbis>`
that I expected.
 
The generated files could be opened with visual studio.
And I could build without any problems.

I appreciate your quick improvement.
🙏

**Comment by hach-que** [comment]
This fix has now been released.
