### ISSUE TITLE
Bad installer

### ISSUE THREAD

**Issue by ANTPro** [Protobuild/Protobuild#240]
![image](https://cloud.githubusercontent.com/assets/273104/25869832/805c49b6-350a-11e7-81e1-80ac85bb48ea.png)

**Comment by hach-que** [comment]
Can you translate what that says?

I just downloaded and ran the installer from the Protobuild website, and it installed and started fine, so my guess is that it's a locale-specific issue.

**Comment by ANTPro** [comment]
Yes, this is a common problem. It is not installed if the user name is not in English. Use UTF8 to fix this error.

**Comment by hach-que** [comment]
We already use UTF8 everywhere.  As far as getting that directory path, we just use the standard .NET APIs: https://github.com/Protobuild/Protobuild/blob/master/Protobuild.Internal/Packages/PackageGlobalTool/PackageGlobalTool.cs#L22

If the username component of the application data path returned from the .NET APIs is wrong, then I'm not really sure how to fix it, as it's the .NET framework returning an invalid path, not something we're doing.

What's the output if you download `Protobuild.exe` from the root of this repo and run the following at a command line:

```
Protobuild.exe --install Protobuild.Manager
```

**Comment by ANTPro** [comment]
Do not use a standard installer - since the installation is not complete (there are no shortcuts to uninstall and select the installation folder). Use NSIS for make good installer.

**Comment by hach-que** [comment]
I need the output from `Protobuild.exe --install Protobuild.Manager` before I can diagnose this issue further.

**Comment by silasary** [comment]
Reproduced.

Log from `Protobuild.exe --install Protobuild.Manager`:  [Log.txt](https://github.com/Protobuild/Protobuild/files/991822/Log.txt)

Note that it does install correctly, and can be found in `C:\Users\しらさり\AppData\Roaming\.protobuild-tools\5f431c21eaee8097b9dca0bdc847c946f66faff1\Protobuild.Manager\AnyCPU`.

The issue is the shortcut in the start menu, which is listing a target of `file:///C:\Users\縺励ｉ縺輔ｊ\AppData\Roaming\.protobuild-tools\5f431c21eaee8097b9dca0bdc847c946f66faff1\Protobuild.Manager\AnyCPU\Protobuild.Manager.exe`.

It appears that the shortcut (a `.url` file) is not UTF-8 encoded.

**Comment by hach-que** [comment]
We're just waiting on the build to finish for that PR, and then this issue should be resolved.
