### ISSUE TITLE
defining additional configurations (ie, 'Shipping')

### ISSUE THREAD

**Issue by jamesford42** [Protobuild/Protobuild#262]
What I would like is to have an additional configuration called 'Shipping' which is the same as the 'Release' configuration except that RELEASE is not defined, and SHIPPING is.

Is this currently possible with protobuild? If not is it a feasible feature to request and/or develop?

**Comment by hach-que** [comment]
We don't currently allow for custom configurations, as the default list of configurations varies between different platforms (for example, iOS generates things like "iOS Simulator" instead of the conventional configurations).

Our recommendation here is to use service dependencies: http://protobuild.readthedocs.io/en/latest/service_dependencies.html. Define a service in your project like this:

```
  <Services>
    <Service Name="Shipping">
      <RemoveDefine>RELEASE</RemoveDefine>
      <AddDefine>SHIPPING</RemoveDefine>
    </Service>
  </Services>
```

Then when you generate your projects, use:

```
Protobuild.exe --generate --enable ProjectName/Shipping
```

**Comment by jamesford42** [comment]
Wouldn't that end up generating a csproj with a Debug and Release config both with SHIPPING defined?

**Comment by hach-que** [comment]
It would, yes.

I assume you're building shipping configurations on a build server somewhere, and you don't need to be switching between these configurations during development.

**Comment by hach-que** [comment]
Closing this issue as there's been no follow-up and as far as I am aware, service dependencies solves this problem.
