### ISSUE TITLE
Download and Website

### ISSUE THREAD

**Issue by felipe98** [Protobuild/Protobuild#264]
Did the website download link change or is the project no longer supported?

**Comment by hach-que** [comment]
We shutdown the website just because the project doesn't see much use these
days.

The major user of the project, MonoGame, has moved away from Protobuild (or
have been in the active process of doing so for a long time now).

MSBuild is now open source, Microsoft is maintaining MonoDevelop / Visual
Studio for Mac (so it's support for complex MSBuild scripts is vastly
improved) and NuGet supports platform specific packages. The .NET ecosystem
is in a much better space than it was when Protobuild was created.

Protobuild isn't officially unsupported, but give it another 6 months of
non-use and we'll probably start shutting it down and archiving projects.
