### ISSUE TITLE
protobuild.org no longer associated with this project

### ISSUE THREAD

**Issue by oblotzky** [Protobuild/Protobuild#265]
This causes quite a number of problems, such as 404 http errors when running the supplied .exe in other projects, and general unavailability of the original sites content.

**Comment by hach-que** [comment]
Can you provide a log of the output that you're seeing, where the lack of
protobuild.org prevents it from running?

**Comment by hach-que** [comment]
Oh, it sounds like MonoGame has an *ancient* version of Protobuild that is
still referencing the Protobuild Index. That's the old package management
system we used before switching this particular dependency over to NuGet in
January 2017. Even back then the Protobuild Index was in read-only mode and
deprecated.

One of the reasons we moved away from the Protobuild Index was precisely so
the app didn't depend on us running and maintaining online infrastructure
forever.

MonoGame should update their Protobuild to something at least newer than
that, and I'd recommend just updating to the latest version.

**Comment by hach-que** [comment]
It should also be noted that the command line invocation of that old
Protobuild version will still work. So --generate, etc should be fine. It's
only because you're not providing invocation arguments that it's trying to
download and launch the interactive GUI.

If you run Protobuild with -help (or --help) you should be able to still
use the command line invocation.

**Comment by oblotzky** [comment]
Okay, makes sense. I was running --generate before, but it didn't produce anything for this project so I assumed it was missing some stuff that it was trying to install after getting from the domain as indicated by the log I posted.

Thanks!

**Comment by hach-que** [comment]
Oh I just noticed you're not running Protobuild from the MonoGame directory
- you're running it from your home directory.

'cd' at the command line to change to the MonoGame directory before running
Protobuild. That should also fix it.

Right now it's because you're specifically running Protobuild with no
arguments in a directory that doesn't have a Protobuild project that is
causing the issue.

**Comment by oblotzky** [comment]
I do feel silly now. Thanks for the help!

I see you already updated the readme to reflect the new website, so I guess this can be marked as resolved then.
